<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeder.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'PHILIBAR',
                'category' => 'BARSTOOL',
                'image' => 'products/Screenshot_270.png',
                'images' => ['products/Screenshot_270.png', 'products/Screenshot_271.png'],
                'type' => 'Chairs, Sofa, Bench',
                'price' => 8900.00,
                'availability' => 'In Stock',
                'date_added' => '2024-01-15',
                'dimensions' => 'W18/D16/H76',
                'material' => 'Indoor: Wood & Metal',
                'description' => 'Modern barstool with ergonomic design and durable construction.',
                'material_options' => [
                    ['label' => 'natural wood', 'value' => 'natural'],
                    ['label' => 'walnut finish', 'value' => 'walnut'],
                ],
                'is_featured' => true,
            ],
            [
                'name' => 'SPARKIE ARM CHAIR',
                'category' => 'CHAIR',
                'image' => 'products/Screenshot_271.png',
                'images' => ['products/Screenshot_271.png', 'products/Screenshot_272.png'],
                'type' => 'Chairs, Sofa, Bench',
                'price' => 12500.00,
                'availability' => 'In Stock',
                'date_added' => '2024-02-10',
                'dimensions' => 'W22/D20/H58',
                'material' => 'Indoor: Upholstered Wood',
                'description' => 'Comfortable arm chair with modern upholstery and solid wood frame.',
                'material_options' => [
                    ['label' => 'fabric upholstery', 'value' => 'fabric'],
                    ['label' => 'leather upholstery', 'value' => 'leather'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'LUGANO WITH HEAD REST',
                'category' => 'CHAIR',
                'image' => 'products/Screenshot_272.png',
                'images' => ['products/Screenshot_272.png', 'products/Screenshot_273.png'],
                'type' => 'Chairs, Sofa, Bench',
                'price' => 15800.00,
                'availability' => 'Out of Stock',
                'date_added' => '2024-02-22',
                'dimensions' => 'W24/D22/H62',
                'material' => 'Indoor: Leather & Steel',
                'description' => 'Executive chair with adjustable headrest and premium leather finish.',
                'material_options' => [
                    ['label' => 'black leather', 'value' => 'black'],
                    ['label' => 'brown leather', 'value' => 'brown'],
                ],
                'is_featured' => true,
            ],
            [
                'name' => 'MODERN DINING TABLE',
                'category' => 'TABLE',
                'image' => 'products/Screenshot_273.png',
                'images' => ['products/Screenshot_273.png', 'products/Screenshot_274.png'],
                'type' => 'Table',
                'price' => 32000.00,
                'availability' => 'In Stock',
                'date_added' => '2024-02-28',
                'dimensions' => 'W180/D90/H75',
                'material' => 'Indoor: Solid Wood',
                'description' => 'Elegant dining table crafted from premium solid wood materials.',
                'material_options' => [
                    ['label' => 'oak finish', 'value' => 'oak'],
                    ['label' => 'mahogany finish', 'value' => 'mahogany'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'BAMBOO PENDANT LIGHT',
                'category' => 'PENDANT',
                'image' => 'products/Screenshot_274.png',
                'images' => ['products/Screenshot_274.png', 'products/Screenshot_275.png'],
                'type' => 'Lighting',
                'price' => 6500.00,
                'availability' => 'In Stock',
                'date_added' => '2024-03-01',
                'dimensions' => 'W25/D25/H30',
                'material' => 'Indoor: Natural Bamboo',
                'description' => 'Eco-friendly pendant light made from sustainable bamboo materials.',
                'material_options' => [
                    ['label' => 'natural finish', 'value' => 'natural'],
                    ['label' => 'dark stain', 'value' => 'dark'],
                ],
                'is_featured' => true,
            ],
            [
                'name' => 'MACKINTOSH',
                'category' => 'CHAIR',
                'image' => 'products/Screenshot_275.png',
                'images' => ['products/Screenshot_275.png', 'products/Screenshot_276.png'],
                'type' => 'Chairs, Sofa, Bench',
                'price' => 11800.00,
                'availability' => 'Out of Stock',
                'date_added' => '2024-03-05',
                'dimensions' => 'W20/D19/H56',
                'material' => 'Indoor: Wood & Metal',
                'description' => 'Designer chair inspired by Mackintosh with geometric elegance.',
                'material_options' => [
                    ['label' => 'black frame', 'value' => 'black'],
                    ['label' => 'chrome frame', 'value' => 'chrome'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'LA BELLA CHAIR',
                'category' => 'CHAIR',
                'image' => 'products/Screenshot_276.png',
                'images' => ['products/Screenshot_276.png', 'products/Screenshot_277.png'],
                'type' => 'Chairs, Sofa, Bench',
                'price' => 9200.00,
                'availability' => 'In Stock',
                'date_added' => '2024-03-12',
                'dimensions' => 'W19/D18/H55',
                'material' => 'Indoor: Upholstered Wood',
                'description' => 'Elegant chair with beautiful curves and comfortable seating.',
                'material_options' => [
                    ['label' => 'velvet upholstery', 'value' => 'velvet'],
                    ['label' => 'linen upholstery', 'value' => 'linen'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'CONFERENCE CHAIR',
                'category' => 'CHAIR',
                'image' => 'products/Screenshot_277.png',
                'images' => ['products/Screenshot_277.png', 'products/Screenshot_278.png'],
                'type' => 'Chairs, Sofa, Bench',
                'price' => 13500.00,
                'availability' => 'In Stock',
                'date_added' => '2024-03-18',
                'dimensions' => 'W22/D21/H60',
                'material' => 'Indoor: Leather & Steel',
                'description' => 'Professional conference chair with executive comfort and style.',
                'material_options' => [
                    ['label' => 'black leather', 'value' => 'black-leather'],
                    ['label' => 'brown leather', 'value' => 'brown-leather'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'BICOL LOUNG CHAIR',
                'category' => 'CHAIR',
                'image' => 'products/Screenshot_278.png',
                'images' => ['products/Screenshot_278.png', 'products/Screenshot_279.png'],
                'type' => 'Chairs, Sofa, Bench',
                'price' => 16800.00,
                'availability' => 'In Stock',
                'date_added' => '2024-04-02',
                'dimensions' => 'W25/D24/H62',
                'material' => 'Indoor: Rattan & Cushion',
                'description' => 'Relaxing lounge chair with traditional Filipino craftsmanship.',
                'material_options' => [
                    ['label' => 'natural rattan', 'value' => 'natural'],
                    ['label' => 'dark rattan', 'value' => 'dark'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'SARI',
                'category' => 'CHAIR',
                'image' => 'products/Screenshot_279.png',
                'images' => ['products/Screenshot_279.png', 'products/Screenshot_280.png'],
                'type' => 'Chairs, Sofa, Bench',
                'price' => 8500.00,
                'availability' => 'Out of Stock',
                'date_added' => '2024-04-08',
                'dimensions' => 'W18/D17/H53',
                'material' => 'Indoor: Woven Fiber',
                'description' => 'Traditional Filipino chair with colorful woven patterns.',
                'material_options' => [
                    ['label' => 'multicolor weave', 'value' => 'multicolor'],
                    ['label' => 'neutral weave', 'value' => 'neutral'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'MBT DUAL-PURPOSE BENCH',
                'category' => 'BENCH',
                'image' => 'products/Screenshot_280.png',
                'images' => ['products/Screenshot_280.png', 'products/Screenshot_281.png'],
                'type' => 'Chairs, Sofa, Bench',
                'price' => 18900.00,
                'availability' => 'In Stock',
                'date_added' => '2024-04-15',
                'dimensions' => 'W45/D18/H45',
                'material' => 'Indoor: Wood & Storage',
                'description' => 'Versatile bench with built-in storage compartment.',
                'material_options' => [
                    ['label' => 'with storage', 'value' => 'storage'],
                    ['label' => 'without storage', 'value' => 'no-storage'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'LOVE SEAT',
                'category' => 'SOFA',
                'image' => 'products/Screenshot_281.png',
                'images' => ['products/Screenshot_281.png', 'products/Screenshot_282.png'],
                'type' => 'Chairs, Sofa, Bench',
                'price' => 22500.00,
                'availability' => 'In Stock',
                'date_added' => '2024-04-20',
                'dimensions' => 'W48/D30/H38',
                'material' => 'Indoor: Upholstered Frame',
                'description' => 'Cozy two-seater sofa perfect for intimate spaces.',
                'material_options' => [
                    ['label' => 'soft cushions', 'value' => 'soft'],
                    ['label' => 'firm cushions', 'value' => 'firm'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'LUCE TABLE LAMP',
                'category' => 'LAMP',
                'image' => 'products/Screenshot_283.png',
                'images' => ['products/Screenshot_283.png', 'products/Screenshot_284.png'],
                'type' => 'Lighting',
                'price' => 4500.00,
                'availability' => 'In Stock',
                'date_added' => '2024-05-01',
                'dimensions' => 'W12/D12/H24',
                'material' => 'Indoor: Metal & Fabric Shade',
                'description' => 'Modern table lamp with adjustable brightness settings.',
                'material_options' => [
                    ['label' => 'white shade', 'value' => 'white'],
                    ['label' => 'black shade', 'value' => 'black'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'STRATOSPHERE',
                'category' => 'LAMP',
                'image' => 'products/Screenshot_284.png',
                'images' => ['products/Screenshot_284.png', 'products/Screenshot_285.png'],
                'type' => 'Lighting',
                'price' => 8200.00,
                'availability' => 'In Stock',
                'date_added' => '2024-05-05',
                'dimensions' => 'W15/D15/H35',
                'material' => 'Indoor: Glass & Metal',
                'description' => 'Spherical pendant lamp with cosmic-inspired design.',
                'material_options' => [
                    ['label' => 'clear glass', 'value' => 'clear'],
                    ['label' => 'frosted glass', 'value' => 'frosted'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'DOY QUAD LANTERN',
                'category' => 'LANTERN',
                'image' => 'products/Screenshot_285.png',
                'images' => ['products/Screenshot_285.png', 'products/Screenshot_286.png'],
                'type' => 'Lighting',
                'price' => 6800.00,
                'availability' => 'Out of Stock',
                'date_added' => '2024-05-10',
                'dimensions' => 'W20/D20/H30',
                'material' => 'Indoor: Recycled Materials',
                'description' => 'Eco-friendly lantern made from upcycled plastic materials.',
                'material_options' => [
                    ['label' => 'warm light', 'value' => 'warm'],
                    ['label' => 'cool light', 'value' => 'cool'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'ROMA',
                'category' => 'LAMP',
                'image' => 'products/Screenshot_286.png',
                'images' => ['products/Screenshot_286.png', 'products/Screenshot_287.png'],
                'type' => 'Lighting',
                'price' => 5200.00,
                'availability' => 'In Stock',
                'date_added' => '2024-05-15',
                'dimensions' => 'W14/D14/H28',
                'material' => 'Indoor: Ceramic & Metal',
                'description' => 'Classical Roman-inspired table lamp with elegant details.',
                'material_options' => [
                    ['label' => 'marble finish', 'value' => 'marble'],
                    ['label' => 'bronze finish', 'value' => 'bronze'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'TORCH LAMP',
                'category' => 'LAMP',
                'image' => 'products/Screenshot_287.png',
                'images' => ['products/Screenshot_287.png', 'products/Screenshot_288.png'],
                'type' => 'Lighting',
                'price' => 7500.00,
                'availability' => 'In Stock',
                'date_added' => '2024-05-20',
                'dimensions' => 'W10/D10/H45',
                'material' => 'Indoor: Wood & LED',
                'description' => 'Torch-style floor lamp with rustic wooden finish.',
                'material_options' => [
                    ['label' => 'natural wood', 'value' => 'natural'],
                    ['label' => 'dark wood', 'value' => 'dark'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'BABYLON',
                'category' => 'LAMP',
                'image' => 'products/Screenshot_288.png',
                'images' => ['products/Screenshot_288.png', 'products/Screenshot_289.png'],
                'type' => 'Lighting',
                'price' => 9500.00,
                'availability' => 'In Stock',
                'date_added' => '2024-05-25',
                'dimensions' => 'W18/D18/H32',
                'material' => 'Indoor: Woven & Metal',
                'description' => 'Hanging garden-style lamp with intricate weave patterns.',
                'material_options' => [
                    ['label' => 'natural weave', 'value' => 'natural'],
                    ['label' => 'colored weave', 'value' => 'colored'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'SLATED LAMP',
                'category' => 'LAMP',
                'image' => 'products/Screenshot_289.png',
                'images' => ['products/Screenshot_289.png', 'products/Screenshot_290.png'],
                'type' => 'Lighting',
                'price' => 6200.00,
                'availability' => 'Out of Stock',
                'date_added' => '2024-06-01',
                'dimensions' => 'W16/D16/H26',
                'material' => 'Indoor: Wood Slats',
                'description' => 'Modern lamp with slatted wood design for ambient lighting.',
                'material_options' => [
                    ['label' => 'wide slats', 'value' => 'wide'],
                    ['label' => 'narrow slats', 'value' => 'narrow'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'KARLA',
                'category' => 'LAMP',
                'image' => 'products/Screenshot_290.png',
                'images' => ['products/Screenshot_290.png', 'products/Screenshot_291.png'],
                'type' => 'Lighting',
                'price' => 5800.00,
                'availability' => 'In Stock',
                'date_added' => '2024-06-05',
                'dimensions' => 'W13/D13/H25',
                'material' => 'Indoor: Ceramic & Linen',
                'description' => 'Elegant ceramic base lamp with soft linen shade.',
                'material_options' => [
                    ['label' => 'white ceramic', 'value' => 'white'],
                    ['label' => 'blue ceramic', 'value' => 'blue'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'AVATAR',
                'category' => 'LAMP',
                'image' => 'products/Screenshot_291.png',
                'images' => ['products/Screenshot_291.png', 'products/Screenshot_292.png'],
                'type' => 'Lighting',
                'price' => 17250.00,
                'availability' => 'In Stock',
                'date_added' => '2024-06-10',
                'dimensions' => 'W22/D22/H65',
                'material' => 'Indoor: Sculptural Metal',
                'description' => 'Artistic floor lamp with futuristic avatar-inspired design.',
                'material_options' => [
                    ['label' => 'matte black', 'value' => 'matte-black'],
                    ['label' => 'polished chrome', 'value' => 'chrome'],
                ],
                'is_featured' => true,
            ],
            [
                'name' => 'ARTEMIO LAMP',
                'category' => 'LAMP',
                'image' => 'products/Screenshot_292.png',
                'images' => ['products/Screenshot_292.png', 'products/Screenshot_293.png'],
                'type' => 'Lighting',
                'price' => 4800.00,
                'availability' => 'In Stock',
                'date_added' => '2024-06-15',
                'dimensions' => 'W11/D11/H22',
                'material' => 'Indoor: Glass & Brass',
                'description' => 'Classic table lamp with brass accents and glass shade.',
                'material_options' => [
                    ['label' => 'clear glass', 'value' => 'clear'],
                    ['label' => 'amber glass', 'value' => 'amber'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'ANDY BANKERS LAMP',
                'category' => 'LAMP',
                'image' => 'products/Screenshot_293.png',
                'images' => ['products/Screenshot_293.png', 'products/Screenshot_294.png'],
                'type' => 'Lighting',
                'price' => 7200.00,
                'availability' => 'Out of Stock',
                'date_added' => '2024-06-20',
                'dimensions' => 'W15/D12/H20',
                'material' => 'Indoor: Brass & Green Glass',
                'description' => 'Traditional banker\'s lamp with green glass shade.',
                'material_options' => [
                    ['label' => 'green shade', 'value' => 'green'],
                    ['label' => 'white shade', 'value' => 'white'],
                ],
                'is_featured' => true,
            ],
            [
                'name' => 'AVATAR 2',
                'category' => 'LAMP',
                'image' => 'products/Screenshot_294.png',
                'images' => ['products/Screenshot_294.png', 'products/Screenshot_295.png'],
                'type' => 'Lighting',
                'price' => 16500.00,
                'availability' => 'In Stock',
                'date_added' => '2024-06-25',
                'dimensions' => 'W20/D20/H62',
                'material' => 'Indoor: Metal & LED',
                'description' => 'Second generation avatar lamp with improved LED technology.',
                'material_options' => [
                    ['label' => 'RGB lighting', 'value' => 'rgb'],
                    ['label' => 'white lighting', 'value' => 'white'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'BOATATING READING LAMP',
                'category' => 'LAMP',
                'image' => 'products/Screenshot_295.png',
                'images' => ['products/Screenshot_295.png', 'products/Screenshot_296.png'],
                'type' => 'Lighting',
                'price' => 8900.00,
                'availability' => 'In Stock',
                'date_added' => '2024-07-01',
                'dimensions' => 'W8/D8/H40',
                'material' => 'Indoor: Adjustable Metal',
                'description' => 'Flexible reading lamp with 360-degree rotation capability.',
                'material_options' => [
                    ['label' => 'desk mount', 'value' => 'desk'],
                    ['label' => 'floor stand', 'value' => 'floor'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'DINING TABLE',
                'category' => 'TABLE',
                'image' => 'products/Screenshot_296.png',
                'images' => ['products/Screenshot_296.png', 'products/Screenshot_297.png'],
                'type' => 'Table',
                'price' => 35000.00,
                'availability' => 'In Stock',
                'date_added' => '2024-07-05',
                'dimensions' => 'W200/D100/H75',
                'material' => 'Indoor: Solid Wood & Steel',
                'description' => 'Elegant dining table with premium wood finish and steel accents.',
                'material_options' => [
                    ['label' => 'walnut finish', 'value' => 'walnut'],
                    ['label' => 'oak finish', 'value' => 'oak'],
                    ['label' => 'teak finish', 'value' => 'teak'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'COFFEE TABLE',
                'category' => 'TABLE',
                'image' => 'products/Screenshot_297.png',
                'images' => ['products/Screenshot_297.png', 'products/Screenshot_298.png'],
                'type' => 'Table',
                'price' => 18500.00,
                'availability' => 'In Stock',
                'date_added' => '2024-07-10',
                'dimensions' => 'W120/D60/H40',
                'material' => 'Indoor: Glass & Metal',
                'description' => 'Modern coffee table with tempered glass top and metal frame.',
                'material_options' => [
                    ['label' => 'clear glass', 'value' => 'clear'],
                    ['label' => 'smoked glass', 'value' => 'smoked'],
                ],
                'is_featured' => true,
            ],
            [
                'name' => 'SIDE TABLE',
                'category' => 'TABLE',
                'image' => 'products/Screenshot_298.png',
                'images' => ['products/Screenshot_298.png', 'products/Screenshot_299.png'],
                'type' => 'Table',
                'price' => 12800.00,
                'availability' => 'Out of Stock',
                'date_added' => '2024-07-15',
                'dimensions' => 'W50/D50/H55',
                'material' => 'Indoor: Marble & Brass',
                'description' => 'Compact side table with marble top and brass legs.',
                'material_options' => [
                    ['label' => 'white marble', 'value' => 'white-marble'],
                    ['label' => 'black marble', 'value' => 'black-marble'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'WORK TABLE',
                'category' => 'TABLE',
                'image' => 'products/Screenshot_299.png',
                'images' => ['products/Screenshot_299.png', 'products/Screenshot_300.png'],
                'type' => 'Table',
                'price' => 28000.00,
                'availability' => 'In Stock',
                'date_added' => '2024-07-20',
                'dimensions' => 'W150/D80/H75',
                'material' => 'Indoor: Engineered Wood & Metal',
                'description' => 'Functional work table with storage compartments and cable management.',
                'material_options' => [
                    ['label' => 'white finish', 'value' => 'white'],
                    ['label' => 'gray finish', 'value' => 'gray'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'CONSOLE TABLE',
                'category' => 'TABLE',
                'image' => 'products/Screenshot_300.png',
                'images' => ['products/Screenshot_300.png', 'products/Screenshot_301.png'],
                'type' => 'Table',
                'price' => 22000.00,
                'availability' => 'In Stock',
                'date_added' => '2024-07-25',
                'dimensions' => 'W120/D35/H80',
                'material' => 'Indoor: Wood & Metal',
                'description' => 'Sleek console table perfect for entryways and hallways.',
                'material_options' => [
                    ['label' => 'natural wood', 'value' => 'natural'],
                    ['label' => 'dark stain', 'value' => 'dark'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'ACCENT TABLE',
                'category' => 'TABLE',
                'image' => 'products/Screenshot_301.png',
                'images' => ['products/Screenshot_301.png', 'products/Screenshot_302.png'],
                'type' => 'Table',
                'price' => 15500.00,
                'availability' => 'In Stock',
                'date_added' => '2024-08-01',
                'dimensions' => 'W45/D35/H45',
                'material' => 'Indoor: Wood & Metal Accent',
                'description' => 'Unique accent table with artistic design elements.',
                'material_options' => [
                    ['label' => 'mahogany finish', 'value' => 'mahogany'],
                    ['label' => 'cherry finish', 'value' => 'cherry'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'MULTIPURPOSE HOLDER',
                'category' => 'ORGANIZER',
                'image' => 'products/Screenshot_302.png',
                'images' => ['products/Screenshot_302.png', 'products/Screenshot_303.png'],
                'type' => 'Accessories, Organizer, Figurine, Mirror',
                'price' => 1800.00,
                'availability' => 'In Stock',
                'date_added' => '2024-08-05',
                'dimensions' => 'W12/D12/H15',
                'material' => 'Indoor: Ceramic & Bamboo',
                'description' => 'Versatile storage solution for small items and accessories.',
                'material_options' => [
                    ['label' => 'white ceramic', 'value' => 'white'],
                    ['label' => 'natural bamboo', 'value' => 'bamboo'],
                ],
                'is_featured' => true,
            ],
            [
                'name' => 'SOAP HOLDER',
                'category' => 'ACCESSORIES',
                'image' => 'products/Screenshot_303.png',
                'images' => ['products/Screenshot_303.png', 'products/Screenshot_304.png'],
                'type' => 'Accessories, Organizer, Figurine, Mirror',
                'price' => 1200.00,
                'availability' => 'In Stock',
                'date_added' => '2024-08-08',
                'dimensions' => 'W10/D7/H3',
                'material' => 'Indoor: Ceramic',
                'description' => 'Elegant soap holder with drainage system for bathroom use.',
                'material_options' => [
                    ['label' => 'white ceramic', 'value' => 'white'],
                    ['label' => 'black ceramic', 'value' => 'black'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'PENCIL HOLDER',
                'category' => 'ORGANIZER',
                'image' => 'products/Screenshot_304.png',
                'images' => ['products/Screenshot_304.png', 'products/Screenshot_305.png'],
                'type' => 'Accessories, Organizer, Figurine, Mirror',
                'price' => 1500.00,
                'availability' => 'Out of Stock',
                'date_added' => '2024-08-10',
                'dimensions' => 'W8/D8/H12',
                'material' => 'Indoor: Wood & Metal',
                'description' => 'Stylish desk organizer for pens, pencils, and stationery.',
                'material_options' => [
                    ['label' => 'natural wood', 'value' => 'natural'],
                    ['label' => 'painted finish', 'value' => 'painted'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'WINE HOLDER',
                'category' => 'ACCESSORIES',
                'image' => 'products/Screenshot_305.png',
                'images' => ['products/Screenshot_305.png', 'products/Screenshot_306.png'],
                'type' => 'Accessories, Organizer, Figurine, Mirror',
                'price' => 2800.00,
                'availability' => 'In Stock',
                'date_added' => '2024-08-12',
                'dimensions' => 'W15/D15/H25',
                'material' => 'Indoor: Metal & Wood',
                'description' => 'Elegant wine bottle holder for single bottle display.',
                'material_options' => [
                    ['label' => 'brass finish', 'value' => 'brass'],
                    ['label' => 'black metal', 'value' => 'black'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'WINE RACK',
                'category' => 'ORGANIZER',
                'image' => 'products/Screenshot_306.png',
                'images' => ['products/Screenshot_306.png', 'products/Screenshot_307.png'],
                'type' => 'Accessories, Organizer, Figurine, Mirror',
                'price' => 4500.00,
                'availability' => 'In Stock',
                'date_added' => '2024-08-15',
                'dimensions' => 'W35/D20/H40',
                'material' => 'Indoor: Solid Wood',
                'description' => 'Multi-bottle wine storage rack with natural wood construction.',
                'material_options' => [
                    ['label' => 'oak wood', 'value' => 'oak'],
                    ['label' => 'pine wood', 'value' => 'pine'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'TOWEL RACK',
                'category' => 'ACCESSORIES',
                'image' => 'products/Screenshot_307.png',
                'images' => ['products/Screenshot_307.png', 'products/Screenshot_308.png'],
                'type' => 'Accessories, Organizer, Figurine, Mirror',
                'price' => 2200.00,
                'availability' => 'In Stock',
                'date_added' => '2024-08-18',
                'dimensions' => 'W60/D8/H80',
                'material' => 'Indoor: Stainless Steel',
                'description' => 'Wall-mounted towel rack with multiple hanging bars.',
                'material_options' => [
                    ['label' => 'polished steel', 'value' => 'polished'],
                    ['label' => 'matte finish', 'value' => 'matte'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'STACKABLE ASHTRAY HOLDER',
                'category' => 'ORGANIZER',
                'image' => 'products/Screenshot_308.png',
                'images' => ['products/Screenshot_308.png', 'products/Screenshot_309.png'],
                'type' => 'Accessories, Organizer, Figurine, Mirror',
                'price' => 1800.00,
                'availability' => 'Out of Stock',
                'date_added' => '2024-08-20',
                'dimensions' => 'W12/D12/H8',
                'material' => 'Indoor: Ceramic',
                'description' => 'Modular ashtray system with stackable design.',
                'material_options' => [
                    ['label' => 'white ceramic', 'value' => 'white'],
                    ['label' => 'gray ceramic', 'value' => 'gray'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'STORAGE BOX',
                'category' => 'ORGANIZER',
                'image' => 'products/Screenshot_320.png',
                'images' => ['products/Screenshot_320.png', 'products/Screenshot_321.png'],
                'type' => 'Accessories, Organizer, Figurine, Mirror',
                'price' => 3200.00,
                'availability' => 'In Stock',
                'date_added' => '2024-08-22',
                'dimensions' => 'W30/D20/H15',
                'material' => 'Indoor: Wood & Fabric',
                'description' => 'Decorative storage box with soft fabric interior.',
                'material_options' => [
                    ['label' => 'linen fabric', 'value' => 'linen'],
                    ['label' => 'velvet fabric', 'value' => 'velvet'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'ARTIST\'S RULER HOLDER',
                'category' => 'ORGANIZER',
                'image' => 'products/Screenshot_309.png',
                'images' => ['products/Screenshot_309.png', 'products/Screenshot_310.png'],
                'type' => 'Accessories, Organizer, Figurine, Mirror',
                'price' => 1600.00,
                'availability' => 'In Stock',
                'date_added' => '2024-08-25',
                'dimensions' => 'W25/D5/H8',
                'material' => 'Indoor: Bamboo',
                'description' => 'Specialized holder for rulers and measuring tools.',
                'material_options' => [
                    ['label' => 'natural bamboo', 'value' => 'natural'],
                    ['label' => 'dark stain', 'value' => 'dark'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'CHOPSTICK HOLDER',
                'category' => 'ACCESSORIES',
                'image' => 'products/Screenshot_310.png',
                'images' => ['products/Screenshot_310.png', 'products/Screenshot_311.png'],
                'type' => 'Accessories, Organizer, Figurine, Mirror',
                'price' => 800.00,
                'availability' => 'In Stock',
                'date_added' => '2024-08-28',
                'dimensions' => 'W8/D8/H10',
                'material' => 'Indoor: Ceramic',
                'description' => 'Traditional chopstick rest and holder for dining.',
                'material_options' => [
                    ['label' => 'white porcelain', 'value' => 'white'],
                    ['label' => 'blue ceramic', 'value' => 'blue'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'DIAMOND PENCIL HOLDER',
                'category' => 'ORGANIZER',
                'image' => 'products/Screenshot_311.png',
                'images' => ['products/Screenshot_311.png', 'products/Screenshot_312.png'],
                'type' => 'Accessories, Organizer, Figurine, Mirror',
                'price' => 1900.00,
                'availability' => 'In Stock',
                'date_added' => '2024-09-01',
                'dimensions' => 'W10/D10/H12',
                'material' => 'Indoor: Crystal & Metal',
                'description' => 'Luxury pencil holder with diamond-cut crystal design.',
                'material_options' => [
                    ['label' => 'clear crystal', 'value' => 'clear'],
                    ['label' => 'colored crystal', 'value' => 'colored'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'TABLET HOLDER',
                'category' => 'ACCESSORIES',
                'image' => 'products/Screenshot_312.png',
                'images' => ['products/Screenshot_312.png', 'products/Screenshot_313.png'],
                'type' => 'Accessories, Organizer, Figurine, Mirror',
                'price' => 2500.00,
                'availability' => 'Out of Stock',
                'date_added' => '2024-09-05',
                'dimensions' => 'W20/D15/H12',
                'material' => 'Indoor: Wood & Metal',
                'description' => 'Adjustable tablet stand for optimal viewing angles.',
                'material_options' => [
                    ['label' => 'bamboo wood', 'value' => 'bamboo'],
                    ['label' => 'aluminum', 'value' => 'aluminum'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'DONG CARPET',
                'category' => 'ACCESSORIES',
                'image' => 'products/Screenshot_313.png',
                'images' => ['products/Screenshot_313.png', 'products/Screenshot_314.png'],
                'type' => 'Accessories, Organizer, Figurine, Mirror',
                'price' => 8500.00,
                'availability' => 'In Stock',
                'date_added' => '2024-09-08',
                'dimensions' => 'W150/D100/H2',
                'material' => 'Indoor: Hand-woven Fiber',
                'description' => 'Artisan carpet with traditional dong pattern weaving.',
                'material_options' => [
                    ['label' => 'natural fiber', 'value' => 'natural'],
                    ['label' => 'dyed fiber', 'value' => 'dyed'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'TANADA SISTERS',
                'category' => 'FIGURINE',
                'image' => 'products/Screenshot_314.png',
                'images' => ['products/Screenshot_314.png', 'products/Screenshot_315.png'],
                'type' => 'Accessories, Organizer, Figurine, Mirror',
                'price' => 3800.00,
                'availability' => 'In Stock',
                'date_added' => '2024-09-10',
                'dimensions' => 'W15/D10/H20',
                'material' => 'Indoor: Ceramic & Paint',
                'description' => 'Decorative figurine set representing the Tanada sisters.',
                'material_options' => [
                    ['label' => 'hand-painted', 'value' => 'painted'],
                    ['label' => 'natural finish', 'value' => 'natural'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'FLOATING CUBE',
                'category' => 'FIGURINE',
                'image' => 'products/Screenshot_315.png',
                'images' => ['products/Screenshot_315.png', 'products/Screenshot_316.png'],
                'type' => 'Accessories, Organizer, Figurine, Mirror',
                'price' => 2200.00,
                'availability' => 'In Stock',
                'date_added' => '2024-09-12',
                'dimensions' => 'W12/D12/H12',
                'material' => 'Indoor: Acrylic & LED',
                'description' => 'Illuminated floating cube with optical illusion effect.',
                'material_options' => [
                    ['label' => 'clear acrylic', 'value' => 'clear'],
                    ['label' => 'tinted acrylic', 'value' => 'tinted'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'KINETIC CUBE',
                'category' => 'FIGURINE',
                'image' => 'products/Screenshot_316.png',
                'images' => ['products/Screenshot_316.png', 'products/Screenshot_317.png'],
                'type' => 'Accessories, Organizer, Figurine, Mirror',
                'price' => 2800.00,
                'availability' => 'In Stock',
                'date_added' => '2024-09-15',
                'dimensions' => 'W10/D10/H10',
                'material' => 'Indoor: Metal & Motor',
                'description' => 'Motorized kinetic sculpture with continuous motion.',
                'material_options' => [
                    ['label' => 'brushed steel', 'value' => 'steel'],
                    ['label' => 'bronze finish', 'value' => 'bronze'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'GOTHIC DIAMOND MIRROR',
                'category' => 'MIRROR',
                'image' => 'products/Screenshot_317.png',
                'images' => ['products/Screenshot_317.png', 'products/Screenshot_318.png'],
                'type' => 'Accessories, Organizer, Figurine, Mirror',
                'price' => 6500.00,
                'availability' => 'Out of Stock',
                'date_added' => '2024-09-18',
                'dimensions' => 'W40/D3/H60',
                'material' => 'Indoor: Glass & Ornate Frame',
                'description' => 'Ornate gothic-style mirror with diamond-shaped frame.',
                'material_options' => [
                    ['label' => 'gold frame', 'value' => 'gold'],
                    ['label' => 'silver frame', 'value' => 'silver'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'SMALL GOTHIC MIRROR',
                'category' => 'MIRROR',
                'image' => 'products/Screenshot_318.png',
                'images' => ['products/Screenshot_318.png', 'products/Screenshot_319.png'],
                'type' => 'Accessories, Organizer, Figurine, Mirror',
                'price' => 4200.00,
                'availability' => 'In Stock',
                'date_added' => '2024-09-20',
                'dimensions' => 'W25/D3/H35',
                'material' => 'Indoor: Glass & Metal Frame',
                'description' => 'Compact gothic mirror perfect for accent decoration.',
                'material_options' => [
                    ['label' => 'antique brass', 'value' => 'brass'],
                    ['label' => 'black metal', 'value' => 'black'],
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'DIAMOND MIRROR',
                'category' => 'MIRROR',
                'image' => 'products/Screenshot_319.png',
                'images' => ['products/Screenshot_319.png', 'products/Screenshot_320.png'],
                'type' => 'Accessories, Organizer, Figurine, Mirror',
                'price' => 5800.00,
                'availability' => 'In Stock',
                'date_added' => '2024-09-22',
                'dimensions' => 'W35/D3/H50',
                'material' => 'Indoor: Mirror & Diamond Frame',
                'description' => 'Elegant diamond-shaped mirror with beveled edges.',
                'material_options' => [
                    ['label' => 'beveled glass', 'value' => 'beveled'],
                    ['label' => 'plain mirror', 'value' => 'plain'],
                ],
                'is_featured' => false,
            ],
        ];

        foreach ($products as $productData) {
            Product::create($productData);
        }
    }
}