export const useAllProducts = [
  // Chairs, Sofa, Bench
  {
    id: 1,
    name: "PHILIBAR",
    category: "CHAIR",
    image: "products/Screenshot_270.png",
    images: ["products/Screenshot_270.png", "products/Screenshot_271.png"],
    type: "Chairs, Sofa, Bench",
    price: 9699,
    availability: "In Stock",
    dateAdded: "2024-01-15",
    dimensions: "W19/D18/H56",
    material: "Indoor: Wood",
    description: "A stylish chair with modern design and comfortable seating.",
    materialOptions: [
      { label: "with cushion", value: "cushion" },
      { label: "without cushion", value: "no-cushion" },
    ],
    isFeatured: true,
  },
  {
    id: 2,
    name: "SPARKIE ARM CHAIR",
    category: "CHAIR",
    image: "products/Screenshot_271.png",
    images: ["products/Screenshot_271.png", "products/Screenshot_272.png"],
    type: "Chairs, Sofa, Bench",
    price: 12500,
    availability: "In Stock",
    dateAdded: "2024-01-20",
    dimensions: "W21/D20/H58",
    material: "Indoor: Wood & Fabric",
    description:
      "Comfortable arm chair with ergonomic design and premium upholstery.",
    materialOptions: [
      { label: "fabric upholstery", value: "fabric" },
      { label: "leather upholstery", value: "leather" },
    ],
  },
  {
    id: 3,
    name: "LUGANO WITH HEAD REST",
    category: "CHAIR",
    image: "products/Screenshot_272.png",
    images: ["products/Screenshot_272.png", "products/Screenshot_273.png"],
    type: "Chairs, Sofa, Bench",
    price: 15200,
    availability: "Out of Stock",
    dateAdded: "2024-02-10",
    dimensions: "W22/D21/H65",
    material: "Indoor: Wood & Cushion",
    description: "High-back chair with head rest support for maximum comfort.",
    materialOptions: [
      { label: "with head cushion", value: "with-cushion" },
      { label: "without head cushion", value: "no-cushion" },
    ],
  },
  {
    id: 4,
    name: "MARCELO",
    category: "CHAIR",
    image: "products/Screenshot_273.png",
    images: ["products/Screenshot_273.png", "products/Screenshot_274.png"],
    type: "Chairs, Sofa, Bench",
    price: 8900,
    availability: "In Stock",
    dateAdded: "2024-02-15",
    dimensions: "W18/D17/H54",
    material: "Indoor: Solid Wood",
    description:
      "Classic wooden chair with traditional craftsmanship and modern appeal.",
    materialOptions: [
      { label: "natural finish", value: "natural" },
      { label: "dark stain", value: "dark" },
    ],
  },
  {
    id: 5,
    name: "LOW BACK SIDE CHAIR",
    category: "CHAIR",
    image: "products/Screenshot_274.png",
    images: ["products/Screenshot_274.png", "products/Screenshot_275.png"],
    type: "Chairs, Sofa, Bench",
    price: 7500,
    availability: "In Stock",
    dateAdded: "2024-02-22",
    dimensions: "W17/D16/H48",
    material: "Indoor: Wood",
    description: "Minimalist low-back chair perfect for dining or office use.",
    materialOptions: [
      { label: "standard height", value: "standard" },
      { label: "bar height", value: "bar" },
    ],
  },
  {
    id: 6,
    name: "MACHINTOCH CHAIR",
    category: "CHAIR",
    image: "products/Screenshot_275.png",
    images: ["products/Screenshot_275.png", "products/Screenshot_276.png"],
    type: "Chairs, Sofa, Bench",
    price: 11800,
    availability: "Out of Stock",
    dateAdded: "2024-03-05",
    dimensions: "W20/D19/H56",
    material: "Indoor: Wood & Metal",
    description:
      "Designer chair inspired by Mackintosh with geometric elegance.",
    materialOptions: [
      { label: "black frame", value: "black" },
      { label: "chrome frame", value: "chrome" },
    ],
  },
  {
    id: 7,
    name: "LA BELLA CHAIR",
    category: "CHAIR",
    image: "products/Screenshot_276.png",
    images: ["products/Screenshot_276.png", "products/Screenshot_277.png"],
    type: "Chairs, Sofa, Bench",
    price: 9200,
    availability: "In Stock",
    dateAdded: "2024-03-12",
    dimensions: "W19/D18/H55",
    material: "Indoor: Upholstered Wood",
    description: "Elegant chair with beautiful curves and comfortable seating.",
    materialOptions: [
      { label: "velvet upholstery", value: "velvet" },
      { label: "linen upholstery", value: "linen" },
    ],
  },
  {
    id: 8,
    name: "CONFERENCE CHAIR",
    category: "CHAIR",
    image: "products/Screenshot_277.png",
    images: ["products/Screenshot_277.png", "products/Screenshot_278.png"],
    type: "Chairs, Sofa, Bench",
    price: 13500,
    availability: "In Stock",
    dateAdded: "2024-03-18",
    dimensions: "W22/D21/H60",
    material: "Indoor: Leather & Steel",
    description:
      "Professional conference chair with executive comfort and style.",
    materialOptions: [
      { label: "black leather", value: "black-leather" },
      { label: "brown leather", value: "brown-leather" },
    ],
  },
  {
    id: 9,
    name: "BICOL LOUNG CHAIR",
    category: "CHAIR",
    image: "products/Screenshot_278.png",
    images: ["products/Screenshot_278.png", "products/Screenshot_279.png"],
    type: "Chairs, Sofa, Bench",
    price: 16800,
    availability: "In Stock",
    dateAdded: "2024-04-02",
    dimensions: "W25/D24/H62",
    material: "Indoor: Rattan & Cushion",
    description:
      "Relaxing lounge chair with traditional Filipino craftsmanship.",
    materialOptions: [
      { label: "natural rattan", value: "natural" },
      { label: "dark rattan", value: "dark" },
    ],
  },
  {
    id: 10,
    name: "SARI",
    category: "CHAIR",
    image: "products/Screenshot_279.png",
    images: ["products/Screenshot_279.png", "products/Screenshot_280.png"],
    type: "Chairs, Sofa, Bench",
    price: 8500,
    availability: "Out of Stock",
    dateAdded: "2024-04-08",
    dimensions: "W18/D17/H53",
    material: "Indoor: Woven Fiber",
    description: "Traditional Filipino chair with colorful woven patterns.",
    materialOptions: [
      { label: "multicolor weave", value: "multicolor" },
      { label: "neutral weave", value: "neutral" },
    ],
  },
  {
    id: 11,
    name: "MBT DUAL-PURPOSE BENCH",
    category: "BENCH",
    image: "products/Screenshot_280.png",
    images: ["products/Screenshot_280.png", "products/Screenshot_281.png"],
    type: "Chairs, Sofa, Bench",
    price: 18900,
    availability: "In Stock",
    dateAdded: "2024-04-15",
    dimensions: "W45/D18/H45",
    material: "Indoor: Wood & Storage",
    description: "Versatile bench with built-in storage compartment.",
    materialOptions: [
      { label: "with storage", value: "storage" },
      { label: "without storage", value: "no-storage" },
    ],
  },
  {
    id: 12,
    name: "LOVE SEAT",
    category: "SOFA",
    image: "products/Screenshot_281.png",
    images: ["products/Screenshot_281.png", "products/Screenshot_282.png"],
    type: "Chairs, Sofa, Bench",
    price: 22500,
    availability: "In Stock",
    dateAdded: "2024-04-20",
    dimensions: "W48/D30/H38",
    material: "Indoor: Upholstered Frame",
    description: "Cozy two-seater sofa perfect for intimate spaces.",
    materialOptions: [
      { label: "soft cushions", value: "soft" },
      { label: "firm cushions", value: "firm" },
    ],
  },

  // Lighting
  {
    id: 13,
    name: "LUCE TABLE LAMP",
    category: "LAMP",
    image: "products/Screenshot_283.png",
    images: ["products/Screenshot_283.png", "products/Screenshot_284.png"],
    type: "Lighting",
    price: 4500,
    availability: "In Stock",
    dateAdded: "2024-05-01",
    dimensions: "W12/D12/H24",
    material: "Indoor: Metal & Fabric Shade",
    description: "Modern table lamp with adjustable brightness settings.",
    materialOptions: [
      { label: "white shade", value: "white" },
      { label: "black shade", value: "black" },
    ],
  },
  {
    id: 14,
    name: "STRATOSPHERE",
    category: "LAMP",
    image: "products/Screenshot_284.png",
    images: ["products/Screenshot_284.png", "products/Screenshot_285.png"],
    type: "Lighting",
    price: 8200,
    availability: "In Stock",
    dateAdded: "2024-05-05",
    dimensions: "W15/D15/H35",
    material: "Indoor: Glass & Metal",
    description: "Spherical pendant lamp with cosmic-inspired design.",
    materialOptions: [
      { label: "clear glass", value: "clear" },
      { label: "frosted glass", value: "frosted" },
    ],
  },
  {
    id: 15,
    name: "DOY QUAD LANTERN",
    category: "LANTERN",
    image: "products/Screenshot_285.png",
    images: ["products/Screenshot_285.png", "products/Screenshot_286.png"],
    type: "Lighting",
    price: 6800,
    availability: "Out of Stock",
    dateAdded: "2024-05-10",
    dimensions: "W20/D20/H30",
    material: "Indoor: Recycled Materials",
    description: "Eco-friendly lantern made from upcycled plastic materials.",
    materialOptions: [
      { label: "warm light", value: "warm" },
      { label: "cool light", value: "cool" },
    ],
  },
  {
    id: 16,
    name: "ROMA",
    category: "LAMP",
    image: "products/Screenshot_286.png",
    images: ["products/Screenshot_286.png", "products/Screenshot_287.png"],
    type: "Lighting",
    price: 5200,
    availability: "In Stock",
    dateAdded: "2024-05-15",
    dimensions: "W14/D14/H28",
    material: "Indoor: Ceramic & Metal",
    description: "Classical Roman-inspired table lamp with elegant details.",
    materialOptions: [
      { label: "marble finish", value: "marble" },
      { label: "bronze finish", value: "bronze" },
    ],
  },
  {
    id: 17,
    name: "TORCH LAMP",
    category: "LAMP",
    image: "products/Screenshot_287.png",
    images: ["products/Screenshot_287.png", "products/Screenshot_288.png"],
    type: "Lighting",
    price: 7500,
    availability: "In Stock",
    dateAdded: "2024-05-20",
    dimensions: "W10/D10/H45",
    material: "Indoor: Wood & LED",
    description: "Torch-style floor lamp with rustic wooden finish.",
    materialOptions: [
      { label: "natural wood", value: "natural" },
      { label: "dark wood", value: "dark" },
    ],
  },
  {
    id: 18,
    name: "BABYLON",
    category: "LAMP",
    image: "products/Screenshot_288.png",
    images: ["products/Screenshot_288.png", "products/Screenshot_289.png"],
    type: "Lighting",
    price: 9500,
    availability: "In Stock",
    dateAdded: "2024-05-25",
    dimensions: "W18/D18/H32",
    material: "Indoor: Woven & Metal",
    description: "Hanging garden-style lamp with intricate weave patterns.",
    materialOptions: [
      { label: "natural weave", value: "natural" },
      { label: "colored weave", value: "colored" },
    ],
  },
  {
    id: 19,
    name: "SLATED LAMP",
    category: "LAMP",
    image: "products/Screenshot_289.png",
    images: ["products/Screenshot_289.png", "products/Screenshot_290.png"],
    type: "Lighting",
    price: 6200,
    availability: "Out of Stock",
    dateAdded: "2024-06-01",
    dimensions: "W16/D16/H26",
    material: "Indoor: Wood Slats",
    description: "Modern lamp with slatted wood design for ambient lighting.",
    materialOptions: [
      { label: "wide slats", value: "wide" },
      { label: "narrow slats", value: "narrow" },
    ],
  },
  {
    id: 20,
    name: "KARLA",
    category: "LAMP",
    image: "products/Screenshot_290.png",
    images: ["products/Screenshot_290.png", "products/Screenshot_291.png"],
    type: "Lighting",
    price: 5800,
    availability: "In Stock",
    dateAdded: "2024-06-05",
    dimensions: "W13/D13/H25",
    material: "Indoor: Ceramic & Linen",
    description: "Elegant ceramic base lamp with soft linen shade.",
    materialOptions: [
      { label: "white ceramic", value: "white" },
      { label: "blue ceramic", value: "blue" },
    ],
  },
  {
    id: 21,
    name: "AVATAR",
    category: "LAMP",
    image: "products/Screenshot_291.png",
    images: ["products/Screenshot_291.png", "products/Screenshot_292.png"],
    type: "Lighting",
    price: 17250,
    availability: "In Stock",
    dateAdded: "2024-06-10",
    dimensions: "W22/D22/H65",
    material: "Indoor: Sculptural Metal",
    description: "Artistic floor lamp with futuristic avatar-inspired design.",
    materialOptions: [
      { label: "matte black", value: "matte-black" },
      { label: "polished chrome", value: "chrome" },
    ],
    isFeatured: true,
  },
  {
    id: 22,
    name: "ARTEMIO LAMP",
    category: "LAMP",
    image: "products/Screenshot_292.png",
    images: ["products/Screenshot_292.png", "products/Screenshot_293.png"],
    type: "Lighting",
    price: 4800,
    availability: "In Stock",
    dateAdded: "2024-06-15",
    dimensions: "W11/D11/H22",
    material: "Indoor: Glass & Brass",
    description: "Classic table lamp with brass accents and glass shade.",
    materialOptions: [
      { label: "clear glass", value: "clear" },
      { label: "amber glass", value: "amber" },
    ],
  },
  {
    id: 23,
    name: "ANDY BANKERS LAMP",
    category: "LAMP",
    image: "products/Screenshot_293.png",
    images: ["products/Screenshot_293.png", "products/Screenshot_294.png"],
    type: "Lighting",
    price: 7200,
    availability: "Out of Stock",
    dateAdded: "2024-06-20",
    dimensions: "W15/D12/H20",
    material: "Indoor: Brass & Green Glass",
    description: "Traditional banker's lamp with green glass shade.",
    materialOptions: [
      { label: "green shade", value: "green" },
      { label: "white shade", value: "white" },
    ],
    isFeatured: true,
  },
  {
    id: 24,
    name: "AVATAR 2",
    category: "LAMP",
    image: "products/Screenshot_294.png",
    images: ["products/Screenshot_294.png", "products/Screenshot_295.png"],
    type: "Lighting",
    price: 16500,
    availability: "In Stock",
    dateAdded: "2024-06-25",
    dimensions: "W20/D20/H62",
    material: "Indoor: Metal & LED",
    description: "Second generation avatar lamp with improved LED technology.",
    materialOptions: [
      { label: "RGB lighting", value: "rgb" },
      { label: "white lighting", value: "white" },
    ],
  },
  {
    id: 25,
    name: "BOATATING READING LAMP",
    category: "LAMP",
    image: "products/Screenshot_295.png",
    images: ["products/Screenshot_295.png", "products/Screenshot_296.png"],
    type: "Lighting",
    price: 8900,
    availability: "In Stock",
    dateAdded: "2024-07-01",
    dimensions: "W8/D8/H40",
    material: "Indoor: Adjustable Metal",
    description: "Flexible reading lamp with 360-degree rotation capability.",
    materialOptions: [
      { label: "desk mount", value: "desk" },
      { label: "floor stand", value: "floor" },
    ],
  },

  // Table
  {
    id: 26,
    name: "DINING TABLE",
    category: "TABLE",
    image: "products/Screenshot_296.png",
    images: ["products/Screenshot_296.png", "products/Screenshot_297.png"],
    type: "Table",
    price: 35000,
    availability: "In Stock",
    dateAdded: "2024-07-05",
    dimensions: "W200/D100/H75",
    material: "Indoor: Solid Wood & Steel",
    description:
      "Elegant dining table with premium wood finish and steel accents.",
    materialOptions: [
      { label: "walnut finish", value: "walnut" },
      { label: "oak finish", value: "oak" },
      { label: "teak finish", value: "teak" },
    ],
  },
  {
    id: 27,
    name: "COFFEE TABLE",
    category: "TABLE",
    image: "products/Screenshot_297.png",
    images: ["products/Screenshot_297.png", "products/Screenshot_298.png"],
    type: "Table",
    price: 18500,
    availability: "In Stock",
    dateAdded: "2024-07-10",
    dimensions: "W120/D60/H40",
    material: "Indoor: Glass & Metal",
    description: "Modern coffee table with tempered glass top and metal frame.",
    materialOptions: [
      { label: "clear glass", value: "clear" },
      { label: "smoked glass", value: "smoked" },
    ],
    isFeatured: true,
  },
  {
    id: 28,
    name: "SIDE TABLE",
    category: "TABLE",
    image: "products/Screenshot_298.png",
    images: ["products/Screenshot_298.png", "products/Screenshot_299.png"],
    type: "Table",
    price: 12800,
    availability: "Out of Stock",
    dateAdded: "2024-07-15",
    dimensions: "W50/D50/H55",
    material: "Indoor: Marble & Brass",
    description: "Compact side table with marble top and brass legs.",
    materialOptions: [
      { label: "white marble", value: "white-marble" },
      { label: "black marble", value: "black-marble" },
    ],
  },
  {
    id: 29,
    name: "WORK TABLE",
    category: "TABLE",
    image: "products/Screenshot_299.png",
    images: ["products/Screenshot_299.png", "products/Screenshot_300.png"],
    type: "Table",
    price: 28000,
    availability: "In Stock",
    dateAdded: "2024-07-20",
    dimensions: "W150/D80/H75",
    material: "Indoor: Engineered Wood & Metal",
    description:
      "Functional work table with storage compartments and cable management.",
    materialOptions: [
      { label: "white finish", value: "white" },
      { label: "gray finish", value: "gray" },
    ],
  },
  {
    id: 30,
    name: "CONSOLE TABLE",
    category: "TABLE",
    image: "products/Screenshot_300.png",
    images: ["products/Screenshot_300.png", "products/Screenshot_301.png"],
    type: "Table",
    price: 22000,
    availability: "In Stock",
    dateAdded: "2024-07-25",
    dimensions: "W120/D35/H80",
    material: "Indoor: Wood & Metal",
    description: "Sleek console table perfect for entryways and hallways.",
    materialOptions: [
      { label: "natural wood", value: "natural" },
      { label: "dark stain", value: "dark" },
    ],
  },
  {
    id: 31,
    name: "ACCENT TABLE",
    category: "TABLE",
    image: "products/Screenshot_301.png",
    images: ["products/Screenshot_301.png", "products/Screenshot_302.png"],
    type: "Table",
    price: 15500,
    availability: "In Stock",
    dateAdded: "2024-08-01",
    dimensions: "W45/D35/H45",
    material: "Indoor: Wood & Metal Accent",
    description: "Unique accent table with artistic design elements.",
    materialOptions: [
      { label: "mahogany finish", value: "mahogany" },
      { label: "cherry finish", value: "cherry" },
    ],
  },

  // Accessories, Organizer, Figurine, Mirror
  {
    id: 32,
    name: "MULTIPURPOSE HOLDER",
    category: "ORGANIZER",
    image: "products/Screenshot_302.png",
    images: ["products/Screenshot_302.png", "products/Screenshot_303.png"],
    type: "Accessories, Organizer, Figurine, Mirror",
    price: 1800,
    availability: "In Stock",
    dateAdded: "2024-08-05",
    dimensions: "W12/D12/H15",
    material: "Indoor: Ceramic & Bamboo",
    description: "Versatile storage solution for small items and accessories.",
    materialOptions: [
      { label: "white ceramic", value: "white" },
      { label: "natural bamboo", value: "bamboo" },
    ],
    isFeatured: true,
  },
  {
    id: 33,
    name: "SOAP HOLDER",
    category: "ACCESSORIES",
    image: "products/Screenshot_303.png",
    images: ["products/Screenshot_303.png", "products/Screenshot_304.png"],
    type: "Accessories, Organizer, Figurine, Mirror",
    price: 1200,
    availability: "In Stock",
    dateAdded: "2024-08-08",
    dimensions: "W10/D7/H3",
    material: "Indoor: Ceramic",
    description: "Elegant soap holder with drainage system for bathroom use.",
    materialOptions: [
      { label: "white ceramic", value: "white" },
      { label: "black ceramic", value: "black" },
    ],
  },
  {
    id: 34,
    name: "PENCIL HOLDER",
    category: "ORGANIZER",
    image: "products/Screenshot_304.png",
    images: ["products/Screenshot_304.png", "products/Screenshot_305.png"],
    type: "Accessories, Organizer, Figurine, Mirror",
    price: 1500,
    availability: "Out of Stock",
    dateAdded: "2024-08-10",
    dimensions: "W8/D8/H12",
    material: "Indoor: Wood & Metal",
    description: "Stylish desk organizer for pens, pencils, and stationery.",
    materialOptions: [
      { label: "natural wood", value: "natural" },
      { label: "painted finish", value: "painted" },
    ],
  },
  {
    id: 35,
    name: "WINE HOLDER",
    category: "ACCESSORIES",
    image: "products/Screenshot_305.png",
    images: ["products/Screenshot_305.png", "products/Screenshot_306.png"],
    type: "Accessories, Organizer, Figurine, Mirror",
    price: 2800,
    availability: "In Stock",
    dateAdded: "2024-08-12",
    dimensions: "W15/D15/H25",
    material: "Indoor: Metal & Wood",
    description: "Elegant wine bottle holder for single bottle display.",
    materialOptions: [
      { label: "brass finish", value: "brass" },
      { label: "black metal", value: "black" },
    ],
  },
  {
    id: 36,
    name: "WINE RACK",
    category: "ORGANIZER",
    image: "products/Screenshot_306.png",
    images: ["products/Screenshot_306.png", "products/Screenshot_307.png"],
    type: "Accessories, Organizer, Figurine, Mirror",
    price: 4500,
    availability: "In Stock",
    dateAdded: "2024-08-15",
    dimensions: "W35/D20/H40",
    material: "Indoor: Solid Wood",
    description:
      "Multi-bottle wine storage rack with natural wood construction.",
    materialOptions: [
      { label: "oak wood", value: "oak" },
      { label: "pine wood", value: "pine" },
    ],
  },
  {
    id: 37,
    name: "TOWEL RACK",
    category: "ACCESSORIES",
    image: "products/Screenshot_307.png",
    images: ["products/Screenshot_307.png", "products/Screenshot_308.png"],
    type: "Accessories, Organizer, Figurine, Mirror",
    price: 2200,
    availability: "In Stock",
    dateAdded: "2024-08-18",
    dimensions: "W60/D8/H80",
    material: "Indoor: Stainless Steel",
    description: "Wall-mounted towel rack with multiple hanging bars.",
    materialOptions: [
      { label: "polished steel", value: "polished" },
      { label: "matte finish", value: "matte" },
    ],
  },
  {
    id: 38,
    name: "STACKABLE ASHTRAY HOLDER",
    category: "ORGANIZER",
    image: "products/Screenshot_308.png",
    images: ["products/Screenshot_308.png", "products/Screenshot_309.png"],
    type: "Accessories, Organizer, Figurine, Mirror",
    price: 1800,
    availability: "Out of Stock",
    dateAdded: "2024-08-20",
    dimensions: "W12/D12/H8",
    material: "Indoor: Ceramic",
    description: "Modular ashtray system with stackable design.",
    materialOptions: [
      { label: "white ceramic", value: "white" },
      { label: "gray ceramic", value: "gray" },
    ],
  },
  {
    id: 39,
    name: "STORAGE BOX",
    category: "ORGANIZER",
    image: "products/Screenshot_320.png",
    images: ["products/Screenshot_320.png", "products/Screenshot_321.png"],
    type: "Accessories, Organizer, Figurine, Mirror",
    price: 3200,
    availability: "In Stock",
    dateAdded: "2024-08-22",
    dimensions: "W30/D20/H15",
    material: "Indoor: Wood & Fabric",
    description: "Decorative storage box with soft fabric interior.",
    materialOptions: [
      { label: "linen fabric", value: "linen" },
      { label: "velvet fabric", value: "velvet" },
    ],
  },
  {
    id: 40,
    name: "ARTIST'S RULER HOLDER",
    category: "ORGANIZER",
    image: "products/Screenshot_309.png",
    images: ["products/Screenshot_309.png", "products/Screenshot_310.png"],
    type: "Accessories, Organizer, Figurine, Mirror",
    price: 1600,
    availability: "In Stock",
    dateAdded: "2024-08-25",
    dimensions: "W25/D5/H8",
    material: "Indoor: Bamboo",
    description: "Specialized holder for rulers and measuring tools.",
    materialOptions: [
      { label: "natural bamboo", value: "natural" },
      { label: "dark stain", value: "dark" },
    ],
  },
  {
    id: 41,
    name: "CHOPSTICK HOLDER",
    category: "ACCESSORIES",
    image: "products/Screenshot_310.png",
    images: ["products/Screenshot_310.png", "products/Screenshot_311.png"],
    type: "Accessories, Organizer, Figurine, Mirror",
    price: 800,
    availability: "In Stock",
    dateAdded: "2024-08-28",
    dimensions: "W8/D8/H10",
    material: "Indoor: Ceramic",
    description: "Traditional chopstick rest and holder for dining.",
    materialOptions: [
      { label: "white porcelain", value: "white" },
      { label: "blue ceramic", value: "blue" },
    ],
  },
  {
    id: 42,
    name: "DIAMOND PENCIL HOLDER",
    category: "ORGANIZER",
    image: "products/Screenshot_311.png",
    images: ["products/Screenshot_311.png", "products/Screenshot_312.png"],
    type: "Accessories, Organizer, Figurine, Mirror",
    price: 1900,
    availability: "In Stock",
    dateAdded: "2024-09-01",
    dimensions: "W10/D10/H12",
    material: "Indoor: Crystal & Metal",
    description: "Luxury pencil holder with diamond-cut crystal design.",
    materialOptions: [
      { label: "clear crystal", value: "clear" },
      { label: "colored crystal", value: "colored" },
    ],
  },
  {
    id: 43,
    name: "TABLET HOLDER",
    category: "ACCESSORIES",
    image: "products/Screenshot_312.png",
    images: ["products/Screenshot_312.png", "products/Screenshot_313.png"],
    type: "Accessories, Organizer, Figurine, Mirror",
    price: 2500,
    availability: "Out of Stock",
    dateAdded: "2024-09-05",
    dimensions: "W20/D15/H12",
    material: "Indoor: Wood & Metal",
    description: "Adjustable tablet stand for optimal viewing angles.",
    materialOptions: [
      { label: "bamboo wood", value: "bamboo" },
      { label: "aluminum", value: "aluminum" },
    ],
  },
  {
    id: 44,
    name: "DONG CARPET",
    category: "ACCESSORIES",
    image: "products/Screenshot_313.png",
    images: ["products/Screenshot_313.png", "products/Screenshot_314.png"],
    type: "Accessories, Organizer, Figurine, Mirror",
    price: 8500,
    availability: "In Stock",
    dateAdded: "2024-09-08",
    dimensions: "W150/D100/H2",
    material: "Indoor: Hand-woven Fiber",
    description: "Artisan carpet with traditional dong pattern weaving.",
    materialOptions: [
      { label: "natural fiber", value: "natural" },
      { label: "dyed fiber", value: "dyed" },
    ],
  },
  {
    id: 45,
    name: "TANADA SISTERS",
    category: "FIGURINE",
    image: "products/Screenshot_314.png",
    images: ["products/Screenshot_314.png", "products/Screenshot_315.png"],
    type: "Accessories, Organizer, Figurine, Mirror",
    price: 3800,
    availability: "In Stock",
    dateAdded: "2024-09-10",
    dimensions: "W15/D10/H20",
    material: "Indoor: Ceramic & Paint",
    description: "Decorative figurine set representing the Tanada sisters.",
    materialOptions: [
      { label: "hand-painted", value: "painted" },
      { label: "natural finish", value: "natural" },
    ],
  },
  {
    id: 46,
    name: "FLOATING CUBE",
    category: "FIGURINE",
    image: "products/Screenshot_315.png",
    images: ["products/Screenshot_315.png", "products/Screenshot_316.png"],
    type: "Accessories, Organizer, Figurine, Mirror",
    price: 2200,
    availability: "In Stock",
    dateAdded: "2024-09-12",
    dimensions: "W12/D12/H12",
    material: "Indoor: Acrylic & LED",
    description: "Illuminated floating cube with optical illusion effect.",
    materialOptions: [
      { label: "clear acrylic", value: "clear" },
      { label: "tinted acrylic", value: "tinted" },
    ],
  },
  {
    id: 47,
    name: "KINETIC CUBE",
    category: "FIGURINE",
    image: "products/Screenshot_316.png",
    images: ["products/Screenshot_316.png", "products/Screenshot_317.png"],
    type: "Accessories, Organizer, Figurine, Mirror",
    price: 2800,
    availability: "In Stock",
    dateAdded: "2024-09-15",
    dimensions: "W10/D10/H10",
    material: "Indoor: Metal & Motor",
    description: "Motorized kinetic sculpture with continuous motion.",
    materialOptions: [
      { label: "brushed steel", value: "steel" },
      { label: "bronze finish", value: "bronze" },
    ],
  },
  {
    id: 48,
    name: "GOTHIC DIAMOND MIRROR",
    category: "MIRROR",
    image: "products/Screenshot_317.png",
    images: ["products/Screenshot_317.png", "products/Screenshot_318.png"],
    type: "Accessories, Organizer, Figurine, Mirror",
    price: 6500,
    availability: "Out of Stock",
    dateAdded: "2024-09-18",
    dimensions: "W40/D3/H60",
    material: "Indoor: Glass & Ornate Frame",
    description: "Ornate gothic-style mirror with diamond-shaped frame.",
    materialOptions: [
      { label: "gold frame", value: "gold" },
      { label: "silver frame", value: "silver" },
    ],
  },
  {
    id: 49,
    name: "SMALL GOTHIC MIRROR",
    category: "MIRROR",
    image: "products/Screenshot_318.png",
    images: ["products/Screenshot_318.png", "products/Screenshot_319.png"],
    type: "Accessories, Organizer, Figurine, Mirror",
    price: 4200,
    availability: "In Stock",
    dateAdded: "2024-09-20",
    dimensions: "W25/D3/H35",
    material: "Indoor: Glass & Metal Frame",
    description: "Compact gothic mirror perfect for accent decoration.",
    materialOptions: [
      { label: "antique brass", value: "brass" },
      { label: "black metal", value: "black" },
    ],
  },
  {
    id: 50,
    name: "DIAMOND MIRROR",
    category: "MIRROR",
    image: "products/Screenshot_319.png",
    images: ["products/Screenshot_319.png", "products/Screenshot_320.png"],
    type: "Accessories, Organizer, Figurine, Mirror",
    price: 5800,
    availability: "In Stock",
    dateAdded: "2024-09-22",
    dimensions: "W35/D3/H50",
    material: "Indoor: Mirror & Diamond Frame",
    description: "Elegant diamond-shaped mirror with beveled edges.",
    materialOptions: [
      { label: "beveled glass", value: "beveled" },
      { label: "plain mirror", value: "plain" },
    ],
  },
];
